package com.tcgdigital.vmcontrol.model;

public enum NotificationType {
    LOCK_ACQUIRED,
    LOCK_RELEASED,
    LOCK_BROKEN,
    ACCESS_REQUESTED,
    ACCESS_GRANTED,
    ACCESS_REVOKED,
    ACCESS_REQUEST_APPROVED,
    ACCESS_REQUEST_DENIED,
    ACCESS_EXPIRING,
    ACCESS_EXPIRED,
    OPERATION_REQUESTED,
    OPERATION_COMPLETED,
    OPERATION_FAILED,
    STATE_DRIFT_DETECTED,
    EKS_SYNC_CHANGED
}
