package com.tcgdigital.vmcontrol.model;

public enum NotificationType {
    LOCK_ACQUIRED,
    LOCK_RELEASED,
    LOCK_BROKEN,
    ACCESS_REQUESTED,
    ACCESS_GRANTED,
    ACCESS_LEVEL_CHANGED,
    ACCESS_REVOKED,
    ACCESS_REQUEST_APPROVED,
    ACCESS_REQUEST_DENIED,
    ACCESS_EXPIRING,
    ACCESS_EXPIRED,
    OPERATION_REQUESTED,
    OPERATION_COMPLETED,
    OPERATION_FAILED,
    STATE_DRIFT_DETECTED,
    EKS_SYNC_CHANGED,
    AUTOMATION_RULE_SKIPPED,
    WEEKLY_COST_REPORT,
    WEEKLY_IDLE_WASTE_REPORT,
    WEEKLY_RIGHTSIZING_REPORT,
    ENVIRONMENT_STOP_NOTICE,
    IDLE_AUTO_STOPPED
}
